#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-scalastyle-maven-plugin
Version  : 1.0.0
Release  : 1
URL      : https://github.com/scalastyle/scalastyle-maven-plugin/archive/v1.0.0.tar.gz
Source0  : https://github.com/scalastyle/scalastyle-maven-plugin/archive/v1.0.0.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/scalastyle/scalastyle-maven-plugin/1.0.0/scalastyle-maven-plugin-1.0.0.jar
Source2  : https://repo.maven.apache.org/maven2/org/scalastyle/scalastyle-maven-plugin/1.0.0/scalastyle-maven-plugin-1.0.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0

%description
## maven-scalastyle-plugin
Welcome to maven-scalastyle-plugin.
This project is intended to provide maven plugin support for Scalastyle.
For more information about Scalastyle, see [https://github.com/scalastyle/scalastyle](https://github.com/scalastyle/scalastyle)

%prep

%build

%install

%files
%defattr(-,root,root,-)
