#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-scalastyle-maven-plugin
Version  : 1.0.0
Release  : 2
URL      : https://github.com/scalastyle/scalastyle-maven-plugin/archive/v1.0.0.tar.gz
Source0  : https://github.com/scalastyle/scalastyle-maven-plugin/archive/v1.0.0.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/scalastyle/scalastyle-maven-plugin/1.0.0/scalastyle-maven-plugin-1.0.0.jar
Source2  : https://repo.maven.apache.org/maven2/org/scalastyle/scalastyle-maven-plugin/1.0.0/scalastyle-maven-plugin-1.0.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-scalastyle-maven-plugin-data = %{version}-%{release}

%description
## maven-scalastyle-plugin
Welcome to maven-scalastyle-plugin.
This project is intended to provide maven plugin support for Scalastyle.
For more information about Scalastyle, see [https://github.com/scalastyle/scalastyle](https://github.com/scalastyle/scalastyle)

%package data
Summary: data components for the mvn-scalastyle-maven-plugin package.
Group: Data

%description data
data components for the mvn-scalastyle-maven-plugin package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scalastyle/scalastyle-maven-plugin/1.0.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/scalastyle/scalastyle-maven-plugin/1.0.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scalastyle/scalastyle-maven-plugin/1.0.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/scalastyle/scalastyle-maven-plugin/1.0.0


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/scalastyle/scalastyle-maven-plugin/1.0.0/scalastyle-maven-plugin-1.0.0.jar
/usr/share/java/.m2/repository/org/scalastyle/scalastyle-maven-plugin/1.0.0/scalastyle-maven-plugin-1.0.0.pom
